language: scala
script:
  - sbt +test +publishLocal plugin/test plugin/scripted
  - jdk_switcher use oraclejdk8 && cd docs && sbt test validateDocs
sudo: false
cache:
  directories:
    - $HOME/.ivy2
